In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [41]:
SPY  = yf.download("SPY" , start= "2005-01-01", end = "2026-03-25")
QQQ  = yf.download("QQQ" , start= "2005-01-01", end = "2026-03-25")
XLE  = yf.download("XLE" , start= "2005-01-01", end = "2026-03-25")
GLD = yf.download("GLD" , start= "2005-01-01", end = "2026-03-25")
TLT  = yf.download("TLT" , start= "2005-01-01", end = "2026-03-25")

C:\Users\Intel\AppData\Local\Temp\ipykernel_28152\3943463099.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  SPY  = yf.download("SPY" , start= "2005-01-01", end = "2026-03-25")
[*********************100%***********************]  1 of 1 completed
C:\Users\Intel\AppData\Local\Temp\ipykernel_28152\3943463099.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  QQQ  = yf.download("QQQ" , start= "2005-01-01", end = "2026-03-25")
[*********************100%***********************]  1 of 1 completed
C:\Users\Intel\AppData\Local\Temp\ipykernel_28152\3943463099.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  XLE  = yf.download("XLE" , start= "2005-01-01", end = "2026-03-25")
[*********************100%***********************]  1 of 1 completed
C:\Users\Intel\AppData\Local\Temp\ipykernel_28152\3943463099.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  GLD = yf.download("GLD" , start= "2005-01-01", end = "2026-03-25")
[*********************100%***********************]  1 of 1 completed
C:\Users\Intel\AppData\Local\Temp\ipykernel_28152\3943463099.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  TLT  = yf.download("TLT" , start= "2005-01-01", end = "2026-03-25")
[*********************100%***********************]  1 of 1 completed

In [43]:
SPY

Price            Close        High         Low        Open     Volume
Ticker             SPY         SPY         SPY         SPY        SPY
Date
2005-01-03   81.383736   82.371435   81.113132   82.236130   55748000
2005-01-04   80.389282   81.546108   80.125445   81.491986   69167600
2005-01-05   79.834526   80.673393   79.827760   80.328373   65667300
2005-01-06   80.240417   80.605732   80.003641   80.125413   47814700
2005-01-07   80.125412   80.659853   79.915692   80.483960   55847700
...                ...         ...         ...         ...        ...
2026-03-18  659.628540  667.895940  659.389203  666.539658   82062600
2026-03-19  658.002991  661.174323  653.385596  655.180681  111272500
2026-03-20  648.570007  656.690002  644.719971  656.510010  163617500
2026-03-23  655.380005  662.619995  653.940002  658.070007  134802700
2026-03-24  653.179993  657.030029  649.880005  651.320007   96457500

[5339 rows x 5 columns]

In [45]:
SPY.columns

MultiIndex([( 'Close', 'SPY'),
            (  'High', 'SPY'),
            (   'Low', 'SPY'),
            (  'Open', 'SPY'),
            ('Volume', 'SPY')],
           names=['Price', 'Ticker'])

In [47]:
column =  [ (  'High', 'SPY'),
            (   'Low', 'SPY'),
            (  'Open', 'SPY'),
            ('Volume', 'SPY')]

In [49]:
SPY = SPY.drop(columns= column)

In [53]:
SPY["Return"] = np.log(SPY[( 'Close', 'SPY')] / SPY[( 'Close', 'SPY')].shift(1))

In [61]:
SPY

Price            Close    Return
Ticker             SPY
Date
2005-01-03   81.383736       NaN
2005-01-04   80.389282 -0.012295
2005-01-05   79.834526 -0.006925
2005-01-06   80.240417  0.005071
2005-01-07   80.125412 -0.001434
...                ...       ...
2026-03-18  659.628540 -0.014052
2026-03-19  658.002991 -0.002467
2026-03-20  648.570007 -0.014440
2026-03-23  655.380005  0.010445
2026-03-24  653.179993 -0.003362

[5339 rows x 2 columns]

In [65]:
SPY = SPY.rename(columns = {'Return': 'SPY_Return'})

In [67]:
SPY

Price            Close SPY_Return
Ticker             SPY
Date
2005-01-03   81.383736        NaN
2005-01-04   80.389282  -0.012295
2005-01-05   79.834526  -0.006925
2005-01-06   80.240417   0.005071
2005-01-07   80.125412  -0.001434
...                ...        ...
2026-03-18  659.628540  -0.014052
2026-03-19  658.002991  -0.002467
2026-03-20  648.570007  -0.014440
2026-03-23  655.380005   0.010445
2026-03-24  653.179993  -0.003362

[5339 rows x 2 columns]

In [71]:
SPY = SPY.drop(columns = [( 'Close', 'SPY')])

In [73]:
SPY

Price      SPY_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.012295
2005-01-05  -0.006925
2005-01-06   0.005071
2005-01-07  -0.001434
...               ...
2026-03-18  -0.014052
2026-03-19  -0.002467
2026-03-20  -0.014440
2026-03-23   0.010445
2026-03-24  -0.003362

[5339 rows x 1 columns]

In [79]:
column =  [ (  'High', 'QQQ'),
            (   'Low', 'QQQ'),
            (  'Open', 'QQQ'),
            ('Volume', 'QQQ')]

In [81]:
QQQ = QQQ.drop(columns= column)

In [89]:
QQQ["Return"] = np.log(QQQ[( 'Close', 'QQQ')] / QQQ[( 'Close', 'QQQ')].shift(1))

In [91]:
QQQ = QQQ.drop(columns = [( 'Close', 'QQQ')])

In [95]:
QQQ = QQQ.rename(columns = {'Return': 'QQQ_Return'})

In [97]:
QQQ

Price      QQQ_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.018396
2005-01-05  -0.006208
2005-01-06  -0.004943
2005-01-07   0.005202
...               ...
2026-03-18  -0.014038
2026-03-19  -0.003165
2026-03-20  -0.018655
2026-03-23   0.011414
2026-03-24  -0.006860

[5339 rows x 1 columns]

In [101]:
column =  [ (  'High', 'XLE'),
            (   'Low', 'XLE'),
            (  'Open', 'XLE'),
            ('Volume', 'XLE')]

In [103]:
XLE = XLE.drop(columns= column)

In [107]:
XLE["Return"] = np.log(XLE[( 'Close', 'XLE')] / XLE[( 'Close', 'XLE')].shift(1))

In [109]:
XLE = XLE.drop(columns = [( 'Close', 'XLE')])

In [111]:
XLE = XLE.rename(columns = {'Return': 'XLE_Return'})

In [113]:
XLE

Price      XLE_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.005159
2005-01-05  -0.004320
2005-01-06   0.017167
2005-01-07  -0.007974
...               ...
2026-03-18  -0.001368
2026-03-19   0.015791
2026-03-20  -0.000843
2026-03-23   0.011893
2026-03-24   0.020089

[5339 rows x 1 columns]

In [115]:
column =  [ (  'High', 'GLD'),
            (   'Low', 'GLD'),
            (  'Open', 'GLD'),
            ('Volume', 'GLD')]

In [117]:
GLD = GLD.drop(columns= column)

In [119]:
GLD["Return"] = np.log(GLD[( 'Close', 'GLD')] / GLD[( 'Close', 'GLD')].shift(1))

In [121]:
GLD = GLD.drop(columns = [( 'Close', 'GLD')])

In [123]:
GLD = GLD.rename(columns = {'Return': 'GLD_Return'})

In [125]:
GLD

Price      GLD_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.006530
2005-01-05  -0.001639
2005-01-06  -0.012261
2005-01-07  -0.007382
...               ...
2026-03-18  -0.032148
2026-03-19  -0.042088
2026-03-20  -0.031034
2026-03-23  -0.022853
2026-03-24   0.000223

[5339 rows x 1 columns]

In [129]:
column =  [ (  'High', 'TLT'),
            (   'Low', 'TLT'),
            (  'Open', 'TLT'),
            ('Volume', 'TLT')]

In [131]:
TLT = TLT.drop(columns= column)

In [133]:
TLT["Return"] = np.log(TLT[( 'Close', 'TLT')] / TLT[( 'Close', 'TLT')].shift(1))

In [135]:
TLT = TLT.drop(columns = [( 'Close', 'TLT')])

In [137]:
TLT = TLT.rename(columns = {'Return': 'TLT_Return'})

In [139]:
TLT

Price      TLT_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.010535
2005-01-05   0.005338
2005-01-06   0.000680
2005-01-07   0.002261
...               ...
2026-03-18  -0.005619
2026-03-19   0.006076
2026-03-20  -0.019156
2026-03-23   0.006503
2026-03-24  -0.004408

[5339 rows x 1 columns]

In [145]:
SPY

Price      SPY_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.012295
2005-01-05  -0.006925
2005-01-06   0.005071
2005-01-07  -0.001434
...               ...
2026-03-18  -0.014052
2026-03-19  -0.002467
2026-03-20  -0.014440
2026-03-23   0.010445
2026-03-24  -0.003362

[5339 rows x 1 columns]

In [147]:
QQQ

Price      QQQ_Return
Ticker
Date
2005-01-03        NaN
2005-01-04  -0.018396
2005-01-05  -0.006208
2005-01-06  -0.004943
2005-01-07   0.005202
...               ...
2026-03-18  -0.014038
2026-03-19  -0.003165
2026-03-20  -0.018655
2026-03-23   0.011414
2026-03-24  -0.006860

[5339 rows x 1 columns]

In [159]:
Portfolio = pd.concat([SPY, QQQ, XLE, GLD, TLT], axis=1)

In [161]:
Portfolio

Price      SPY_Return QQQ_Return XLE_Return GLD_Return TLT_Return
Ticker
Date
2005-01-03        NaN        NaN        NaN        NaN        NaN
2005-01-04  -0.012295  -0.018396  -0.005159  -0.006530  -0.010535
2005-01-05  -0.006925  -0.006208  -0.004320  -0.001639   0.005338
2005-01-06   0.005071  -0.004943   0.017167  -0.012261   0.000680
2005-01-07  -0.001434   0.005202  -0.007974  -0.007382   0.002261
...               ...        ...        ...        ...        ...
2026-03-18  -0.014052  -0.014038  -0.001368  -0.032148  -0.005619
2026-03-19  -0.002467  -0.003165   0.015791  -0.042088   0.006076
2026-03-20  -0.014440  -0.018655  -0.000843  -0.031034  -0.019156
2026-03-23   0.010445   0.011414   0.011893  -0.022853   0.006503
2026-03-24  -0.003362  -0.006860   0.020089   0.000223  -0.004408

[5339 rows x 5 columns]

In [165]:
Portfolio.to_csv("Portfolio_Return.csv")